### PR TITLE
GitHub

### PR DESCRIPTION
**Pull request by willrogers**
@ifmalcuaz let's get Travis set up on this branch.

### CODE REVIEW

**Comment by willrogers** [comment]
I force-pushed a commit to trigger the Travis build, so you'll have to resolve that.

I think Travis builds have been slow recently, so it might not run immediately.

**Comment by ifmalcuaz** [comment]
@willrogers Looks like I don't have push access to this repo; I'll have to fork it

**Comment by willrogers** [comment]
You should have permission now - try pushing to this branch.

**Comment by willrogers** [comment]
You could add Travis and Coveralls badges to the README. I have enabled Coveralls for this repo but it will need another commit to trigger a check.

https://coveralls.io/github/dls-controls/pyburt

**Comment by willrogers** [comment]
Travis badge?

**Pull request merged**
